//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GlobalRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalRes() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Auction.App_LocalResources.GlobalRes", typeof(GlobalRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Мыло.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отображение даты, времени и языка.
        /// </summary>
        public static string LocalAndZone {
            get {
                return ResourceManager.GetString("LocalAndZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Телефон.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Автомобили.
        /// </summary>
        public static string Автомобили {
            get {
                return ResourceManager.GetString("Автомобили", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Администратор.
        /// </summary>
        public static string Администратор {
            get {
                return ResourceManager.GetString("Администратор", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Адресс.
        /// </summary>
        public static string Адресс {
            get {
                return ResourceManager.GetString("Адресс", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на А может не надо.
        /// </summary>
        public static string АМожетНеНадо {
            get {
                return ResourceManager.GetString("АМожетНеНадо", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Англиский.
        /// </summary>
        public static string Англиский {
            get {
                return ResourceManager.GetString("Англиский", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Англия.
        /// </summary>
        public static string Англия {
            get {
                return ResourceManager.GetString("Англия", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Аукцион.
        /// </summary>
        public static string Аукцион {
            get {
                return ResourceManager.GetString("Аукцион", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на А что разве не видно что аукцион закончился еще в том году? Лан посмотри другие.
        /// </summary>
        public static string АЧтоРазвеНеВидноЧтоАукционЗакончилсяЕщеВТомГодуЛанПосмотриДругие {
            get {
                return ResourceManager.GetString("АЧтоРазвеНеВидноЧтоАукционЗакончилсяЕщеВТомГодуЛанПосмотриДругие", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Беларуский.
        /// </summary>
        public static string Беларуский {
            get {
                return ResourceManager.GetString("Беларуский", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Беларусь.
        /// </summary>
        public static string Беларусь {
            get {
                return ResourceManager.GetString("Беларусь", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Внатуре удалишь.
        /// </summary>
        public static string ВнатуреУдалишь {
            get {
                return ResourceManager.GetString("ВнатуреУдалишь", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Время до окончания.
        /// </summary>
        public static string ВремяДоОкончания {
            get {
                return ResourceManager.GetString("ВремяДоОкончания", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Всего 2 поля, и то умудрился не все заполнить.
        /// </summary>
        public static string Всего2Поля {
            get {
                return ResourceManager.GetString("Всего2Поля", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Все продукты Banned.
        /// </summary>
        public static string ВсеПродуктыBanned {
            get {
                return ResourceManager.GetString("ВсеПродуктыBanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вход.
        /// </summary>
        public static string Вход {
            get {
                return ResourceManager.GetString("Вход", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выбрать категорию.
        /// </summary>
        public static string ВыбратьКатегорию {
            get {
                return ResourceManager.GetString("ВыбратьКатегорию", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на А давай мы выставим это навсегда?.
        /// </summary>
        public static string ВыставимНавсегда {
            get {
                return ResourceManager.GetString("ВыставимНавсегда", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Давай не будем.
        /// </summary>
        public static string ДавайНеБудем {
            get {
                return ResourceManager.GetString("ДавайНеБудем", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дать добро.
        /// </summary>
        public static string ДатьДобро {
            get {
                return ResourceManager.GetString("ДатьДобро", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Для тех, кому не понятно.
        /// </summary>
        public static string ДляТехКомуНеПонятно {
            get {
                return ResourceManager.GetString("ДляТехКомуНеПонятно", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить.
        /// </summary>
        public static string Добавить {
            get {
                return ResourceManager.GetString("Добавить", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить категорию.
        /// </summary>
        public static string ДобавитьКатегорию {
            get {
                return ResourceManager.GetString("ДобавитьКатегорию", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить новый.
        /// </summary>
        public static string ДобавитьНовый {
            get {
                return ResourceManager.GetString("ДобавитьНовый", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить продукт.
        /// </summary>
        public static string ДобавитьПродукт {
            get {
                return ResourceManager.GetString("ДобавитьПродукт", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добро пожаловать на аукцион.
        /// </summary>
        public static string ДоброПожаловать {
            get {
                return ResourceManager.GetString("ДоброПожаловать", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Домашняя.
        /// </summary>
        public static string Домашняя {
            get {
                return ResourceManager.GetString("Домашняя", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Да побереги ты деньги.
        /// </summary>
        public static string ДПоберегиТыДеньги {
            get {
                return ResourceManager.GetString("ДПоберегиТыДеньги", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Зарегистрированые пользователи.
        /// </summary>
        public static string ЗарегистрированыеПользователи {
            get {
                return ResourceManager.GetString("ЗарегистрированыеПользователи", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не заполнишь логин, зарегишся как &apos;Бумбараш&apos;.
        /// </summary>
        public static string ЗарегишсяБумбараш {
            get {
                return ResourceManager.GetString("ЗарегишсяБумбараш", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Зачем удаляешь? Может он человек хороший.
        /// </summary>
        public static string ЗачемУдаляешьМожетОнЧеловекХороший {
            get {
                return ResourceManager.GetString("ЗачемУдаляешьМожетОнЧеловекХороший", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ну и конечно игрушки для взрослых.
        /// </summary>
        public static string ИгрушкиДляВзрослых {
            get {
                return ResourceManager.GetString("ИгрушкиДляВзрослых", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Изменить.
        /// </summary>
        public static string Изменить {
            get {
                return ResourceManager.GetString("Изменить", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Изменить пароль.
        /// </summary>
        public static string ИзменитьПароль {
            get {
                return ResourceManager.GetString("ИзменитьПароль", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Изменить Имя и Фамилию.
        /// </summary>
        public static string ИзменитьФамилиюИмя {
            get {
                return ResourceManager.GetString("ИзменитьФамилиюИмя", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Изображение.
        /// </summary>
        public static string Изображение {
            get {
                return ResourceManager.GetString("Изображение", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя.
        /// </summary>
        public static string Имя {
            get {
                return ResourceManager.GetString("Имя", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя и Фамилия.
        /// </summary>
        public static string ИмяИФамилия {
            get {
                return ResourceManager.GetString("ИмяИФамилия", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Какие ставки? У тебя же денег нет.
        /// </summary>
        public static string КакиеСтавкиУТебяДенегНет {
            get {
                return ResourceManager.GetString("КакиеСтавкиУТебяДенегНет", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ну и как это чудо называть?.
        /// </summary>
        public static string КакНазывать {
            get {
                return ResourceManager.GetString("КакНазывать", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ну хоть как нибудь поясни, мало ли туговатых... не поймут еще.
        /// </summary>
        public static string какНибудьПоясни {
            get {
                return ResourceManager.GetString("какНибудьПоясни", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на И на каком языке с вами общаться?.
        /// </summary>
        public static string КакойЯзык {
            get {
                return ResourceManager.GetString("КакойЯзык", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Категорий не обнаружено.
        /// </summary>
        public static string КатегорийНеОбнаружено {
            get {
                return ResourceManager.GetString("КатегорийНеОбнаружено", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Категория.
        /// </summary>
        public static string Категория {
            get {
                return ResourceManager.GetString("Категория", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Контакты.
        /// </summary>
        public static string Контакты {
            get {
                return ResourceManager.GetString("Контакты", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Личный кабинет.
        /// </summary>
        public static string ЛичныйКабинет {
            get {
                return ResourceManager.GetString("ЛичныйКабинет", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Логин.
        /// </summary>
        public static string Логин {
            get {
                return ResourceManager.GetString("Логин", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Менеджер.
        /// </summary>
        public static string Менеджер {
            get {
                return ResourceManager.GetString("Менеджер", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Мобильные телефоны.
        /// </summary>
        public static string МобильныеТелефоны {
            get {
                return ResourceManager.GetString("МобильныеТелефоны", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Может не надо? А?.
        /// </summary>
        public static string МожетНеНадо {
            get {
                return ResourceManager.GetString("МожетНеНадо", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Мои товары.
        /// </summary>
        public static string МоиТовары {
            get {
                return ResourceManager.GetString("МоиТовары", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на На главную.
        /// </summary>
        public static string НаГлавную {
            get {
                return ResourceManager.GetString("НаГлавную", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Назад.
        /// </summary>
        public static string Назад {
            get {
                return ResourceManager.GetString("Назад", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название.
        /// </summary>
        public static string Название {
            get {
                return ResourceManager.GetString("Название", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Начальная цена.
        /// </summary>
        public static string НачальнаяЦена {
            get {
                return ResourceManager.GetString("НачальнаяЦена", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Незнаешь во сколько оценить?.
        /// </summary>
        public static string НезнаешьВоСколькоОценить {
            get {
                return ResourceManager.GetString("НезнаешьВоСколькоОценить", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ни че не пропустил?.
        /// </summary>
        public static string НиЧеНеПропустил {
            get {
                return ResourceManager.GetString("НиЧеНеПропустил", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ну вот... еще на одного стало больше.
        /// </summary>
        public static string НуВотЕщеНаОдногоСталоБольше {
            get {
                return ResourceManager.GetString("НуВотЕщеНаОдногоСталоБольше", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ну давай уже добавим.
        /// </summary>
        public static string НуДавайУжеДобавим {
            get {
                return ResourceManager.GetString("НуДавайУжеДобавим", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ну и где нам потом вас искать?.
        /// </summary>
        public static string НуИГдеВЫНаходитесь {
            get {
                return ResourceManager.GetString("НуИГдеВЫНаходитесь", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Одежда.
        /// </summary>
        public static string Одежда {
            get {
                return ResourceManager.GetString("Одежда", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Одумайся.
        /// </summary>
        public static string Одумайся {
            get {
                return ResourceManager.GetString("Одумайся", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Одумайся!!! он тебя подсидит.
        /// </summary>
        public static string ОдумайсяОнТебяПодсидит {
            get {
                return ResourceManager.GetString("ОдумайсяОнТебяПодсидит", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Окончание регистрации.
        /// </summary>
        public static string ОкончаниеРегистрации {
            get {
                return ResourceManager.GetString("ОкончаниеРегистрации", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Описание.
        /// </summary>
        public static string Описание {
            get {
                return ResourceManager.GetString("Описание", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на О себе любимом.
        /// </summary>
        public static string ОСебеЛюбимом {
            get {
                return ResourceManager.GetString("ОСебеЛюбимом", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пароль.
        /// </summary>
        public static string Пароль {
            get {
                return ResourceManager.GetString("Пароль", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Персональные Данные.
        /// </summary>
        public static string ПерсональныеДанные {
            get {
                return ResourceManager.GetString("ПерсональныеДанные", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на На столько плохое имя, что не заполнил?.
        /// </summary>
        public static string ПлохоеИмя {
            get {
                return ResourceManager.GetString("ПлохоеИмя", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Повысить статус пользователя.
        /// </summary>
        public static string ПовыситьСтатусПользователя {
            get {
                return ResourceManager.GetString("ПовыситьСтатусПользователя", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поздравляю.
        /// </summary>
        public static string Поздравляю {
            get {
                return ResourceManager.GetString("Поздравляю", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Показать все продукты.
        /// </summary>
        public static string ПоказатьВсеПродукты {
            get {
                return ResourceManager.GetString("ПоказатьВсеПродукты", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Показать категории.
        /// </summary>
        public static string ПоказатьКатегории {
            get {
                return ResourceManager.GetString("ПоказатьКатегории", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Показать отчет по BANNED продуктам.
        /// </summary>
        public static string ПоказатьОтчетПоBANNEDПродуктам {
            get {
                return ResourceManager.GetString("ПоказатьОтчетПоBANNEDПродуктам", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на А ни чего, что это поле нужно заполнить?.
        /// </summary>
        public static string ПолеНужноЗаполнить {
            get {
                return ResourceManager.GetString("ПолеНужноЗаполнить", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Правильно, деньги целее будут.
        /// </summary>
        public static string ПравильноДеньгиЦелееБудут {
            get {
                return ResourceManager.GetString("ПравильноДеньгиЦелееБудут", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Применить.
        /// </summary>
        public static string Применить {
            get {
                return ResourceManager.GetString("Применить", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Продлить аукцион.
        /// </summary>
        public static string ПродлитьАукцион {
            get {
                return ResourceManager.GetString("ПродлитьАукцион", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Продолжительность.
        /// </summary>
        public static string Продолжительность {
            get {
                return ResourceManager.GetString("Продолжительность", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Продолжительность до...позавчера? Ну молодец.
        /// </summary>
        public static string ПродолжительностьДоПозавчера {
            get {
                return ResourceManager.GetString("ПродолжительностьДоПозавчера", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Внимание!!! Все продукты данной категории будут удалены..
        /// </summary>
        public static string ПродуктыКатегорииУдалены {
            get {
                return ResourceManager.GetString("ПродуктыКатегорииУдалены", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Просмотреть всех пользователей.
        /// </summary>
        public static string ПросмотретьВсехПользователей {
            get {
                return ResourceManager.GetString("ПросмотретьВсехПользователей", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Просмотреть список выставленных своих товаров.
        /// </summary>
        public static string ПросмотретьСписокВыставленныхСвоихТоваров {
            get {
                return ResourceManager.GetString("ПросмотретьСписокВыставленныхСвоихТоваров", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Просмотреть список моих ставок.
        /// </summary>
        public static string ПросмотретьСписокМоихСтавок {
            get {
                return ResourceManager.GetString("ПросмотретьСписокМоихСтавок", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Просмотреть список ставок.
        /// </summary>
        public static string ПросмотретьСписокСтавок {
            get {
                return ResourceManager.GetString("ПросмотретьСписокСтавок", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Регистрация.
        /// </summary>
        public static string Регистрация {
            get {
                return ResourceManager.GetString("Регистрация", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Регистрация успешно завершина, вы можете войти под своим .
        /// </summary>
        public static string РегистрацияЗавершена {
            get {
                return ResourceManager.GetString("РегистрацияЗавершена", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Редактирование категорий.
        /// </summary>
        public static string РедактированиеКатегорий {
            get {
                return ResourceManager.GetString("РедактированиеКатегорий", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Редактировать.
        /// </summary>
        public static string Редактировать {
            get {
                return ResourceManager.GetString("Редактировать", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Редактировать личные данные.
        /// </summary>
        public static string РедактироватьЛичныеДанные {
            get {
                return ResourceManager.GetString("РедактироватьЛичныеДанные", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Россия.
        /// </summary>
        public static string Россия {
            get {
                return ResourceManager.GetString("Россия", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Русский.
        /// </summary>
        public static string Русский {
            get {
                return ResourceManager.GetString("Русский", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сделать ставку.
        /// </summary>
        public static string СделатьСтавку {
            get {
                return ResourceManager.GetString("СделатьСтавку", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Слезно попрасить Админа о повышении статуса.
        /// </summary>
        public static string СлезноПопраситьАдминаОПовышенииСтатуса {
            get {
                return ResourceManager.GetString("СлезноПопраситьАдминаОПовышенииСтатуса", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранить.
        /// </summary>
        public static string Сохранить {
            get {
                return ResourceManager.GetString("Сохранить", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Статус.
        /// </summary>
        public static string Статус {
            get {
                return ResourceManager.GetString("Статус", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Стыдно даже описывать, то, что выставляешь?.
        /// </summary>
        public static string СтыдноОписывать {
            get {
                return ResourceManager.GetString("СтыдноОписывать", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тебе оно надо ?.
        /// </summary>
        public static string ТебеОноНадо {
            get {
                return ResourceManager.GetString("ТебеОноНадо", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Текущая цена.
        /// </summary>
        public static string ТекущаяЦена {
            get {
                return ResourceManager.GetString("ТекущаяЦена", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Товар.
        /// </summary>
        public static string Товар {
            get {
                return ResourceManager.GetString("Товар", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Товары.
        /// </summary>
        public static string Товары {
            get {
                return ResourceManager.GetString("Товары", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ты даже удалить толком ничего не можешь.
        /// </summary>
        public static string ТыДажеУдалитьТолкомНичегоНеМожешь {
            get {
                return ResourceManager.GetString("ТыДажеУдалитьТолкомНичегоНеМожешь", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ты с нами.
        /// </summary>
        public static string ТыСНами {
            get {
                return ResourceManager.GetString("ТыСНами", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ты точно хочешь его повысить?.
        /// </summary>
        public static string ТыТочноХочешьЕгоПовысить {
            get {
                return ResourceManager.GetString("ТыТочноХочешьЕгоПовысить", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удаление пользователя.
        /// </summary>
        public static string УдалениеПользователя {
            get {
                return ResourceManager.GetString("УдалениеПользователя", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить.
        /// </summary>
        public static string Удалить {
            get {
                return ResourceManager.GetString("Удалить", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить аккаунт.
        /// </summary>
        public static string УдалитьАккаунт {
            get {
                return ResourceManager.GetString("УдалитьАккаунт", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить продукт.
        /// </summary>
        public static string УдалитьПродукт {
            get {
                return ResourceManager.GetString("УдалитьПродукт", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Да укажи хотя бы не свою.
        /// </summary>
        public static string УкажитеФамилию {
            get {
                return ResourceManager.GetString("УкажитеФамилию", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на У нас уже такой есть, будь оригинальным.
        /// </summary>
        public static string УНасУжеТакойЕсть {
            get {
                return ResourceManager.GetString("УНасУжеТакойЕсть", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фамилия.
        /// </summary>
        public static string Фамилия {
            get {
                return ResourceManager.GetString("Фамилия", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Хоть левую фотку, но нужно прикрепить.
        /// </summary>
        public static string ФоткуНужноПрикрепить {
            get {
                return ResourceManager.GetString("ФоткуНужноПрикрепить", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Часовой пояс.
        /// </summary>
        public static string ЧасовойПояс {
            get {
                return ResourceManager.GetString("ЧасовойПояс", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Что не проскочил? Ну давай поугадывай еще))).
        /// </summary>
        public static string ЧтоНеПроскочил {
            get {
                return ResourceManager.GetString("ЧтоНеПроскочил", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Что убегаешь?.
        /// </summary>
        public static string ЧтоУбегаешь {
            get {
                return ResourceManager.GetString("ЧтоУбегаешь", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Шаг ставки.
        /// </summary>
        public static string ШагСтавки {
            get {
                return ResourceManager.GetString("ШагСтавки", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Язык.
        /// </summary>
        public static string Язык {
            get {
                return ResourceManager.GetString("Язык", resourceCulture);
            }
        }
    }
}
